# Site settings
title: kiiBoss
email: trent@kiiboss.studio
description: Copyright 2019
#url: "https://kiiboss.studio" # the base hostname & protocol for your site
twitter_username: Snipcart
github_username:  Snipcart
api_key: YjcxNTI4Y2MtZGUyOC00YjdjLWE3ZTYtNTMwNTgyMzA2M2QwNjM2ODc5NTEzMzg1NTM4OTcy

# Build settings
markdown: kramdown
collections:
  products:
    output: true
